### ISSUE TITLE
NewsFeed

### ISSUE THREAD

**Issue by ViniciaLaraRangel** [jetzable/cdmx-2018-06-bc-core-am-social-network#24]
1.  - [x] Maqueta html/css de acuerdo a sketch con lo siguiente:

-  - [ ] Logo de la marca.
-  - [ ] Card p/publicación de usuario c/ icono(botón) de "me apetece", "compartir", "eliminar" y "editar"
-  - [ ] Navbar horizontal inferior fija y con iconos de "usuario", "amigos", "me apetece" y "salir". Es opcional el input de búsqueda y botón para detonar el evento. 

2.  - [ ] Funcionalidad 

-  - [ ] Muestra muro
-  - [ ] Permite publicar nuevos post
-  - [ ] Pide confirmación antes de borrar post
-  - [ ] Permite editar post (in place)
-  - [ ] Permite filtrar post por público/amigos
-  - [ ] Permite marcar post como gustados (me like)

**Comment by jetzable** [comment]
Tareas Completadas.
