### ISSUE TITLE
Read Me

### ISSUE THREAD

**Issue by ViniciaLaraRangel** [jetzable/cdmx-2018-06-bc-core-am-social-network#25]
1. - [x] General

- - [ ]   Descripción y alcance del producto
- - [ ] Instalación
- - [ ] ¿Cómo loguearse en nuestra red?
- - [ ] Features

2. - [ ] UX

- - [ ] Introducción
- - [ ] Preambulo
- - [ ] Herramientas de análisis de mercado
- - [ ] Sketching
- - [ ] Herramientas del equipo de desarrollo

**Comment by Copelia** [comment]
Todas las tareas fueron completadas.
